
const dataSets = {
    coin: [{"id":"xxzBTdZJm9Q", "data": [
        {title: 'Quiz01 1',  image: '/coins/russia-100-rubles-1993-ob.png'},
        {title: 'Quiz01 2', image: '/coins/russia-100-rubles-1993-rev.png'},
        {title: 'Quiz01 3',  image: '/coins/russia-100-rubles-1993-ob.png'},
        {title: 'Quiz01 4', image: '/coins/russia-100-rubles-1993-rev.png'},
        {title: 'Quiz01 5',  image: '/coins/russia-100-rubles-1993-ob.png'},
        {title: 'Quiz01 6', image: '/coins/russia-100-rubles-1993-rev.png'},
        {title: 'Quiz01 7',  image: '/coins/russia-100-rubles-1993-ob.png'},
        {title: 'Quiz01 8', image: '/coins/russia-100-rubles-1993-rev.png'},
        {title: 'Quiz01 9',  image: '/coins/russia-100-rubles-1993-ob.png'},
        {title: 'Quiz01 10', image: '/coins/russia-100-rubles-1993-rev.png'},
        {title: 'Quiz01 11', image: '/coins/coin-gurt.png'},
    ]},
    {"id":"k85mRPqvMbE", "data": [
        {title: 'Quiz02 1',  image: '/imp/4.png'},
        {title: 'Quiz02 2', image: '/imp/5.png'},
        {title: 'Quiz02 3',  image: '/imp/6.png'},
        {title: 'Quiz02 4', image: '/imp/7.png'},
        {title: 'Quiz02 5',  image: '/imp/8.png'},
    ]}, {"id":"vVkfxIlZFY0", "data": [
        {title: 'Quiz03 1',  image: '/imp/4.png'},
        {title: 'Quiz03 2', image: '/imp/5.png'},
        {title: 'Quiz03 3',  image: '/imp/6.png'},
        {title: 'Quiz03 4', image: '/imp/7.png'},
        {title: 'Quiz03 5',  image: '/imp/8.png'},
        {title: 'Quiz03 6',  image: '/imp/9.png'},
    ]},
    {"id":"ym9UXX8oyTg", "data": [
        {title: 'Quiz04 1',  image: '/imp/4.png'},
        {title: 'Quiz04 2', image: '/imp/5.png'},
        {title: 'Quiz04 3',  image: '/imp/6.png'},
        {title: 'Quiz04 4', image: '/imp/7.png'},
        {title: 'Quiz04 5',  image: '/imp/8.png'},
        {title: 'Quiz04 6',  image: '/imp/9.png'},
    ]},
    {"id":"OHXf7wEpBPI", "data": [
        {title: 'Quiz05 1',  image: '/imp/4.png'},
        {title: 'Quiz05 2', image: '/imp/5.png'},
        {title: 'Quiz05 3',  image: '/imp/6.png'},
        {title: 'Quiz05 4', image: '/imp/7.png'},
        {title: 'Quiz05 5',  image: '/imp/8.png'},
        {title: 'Quiz05 6',  image: '/imp/9.png'},
    ]},
    {"id":"52Gg9CqhbP8", "data": [
        {title: 'Quiz06 1',  image: '/imp/4.png'},
        {title: 'Quiz06 2', image: '/imp/5.png'},
        {title: 'Quiz06 3',  image: '/imp/6.png'},
        {title: 'Quiz06 4', image: '/imp/7.png'},
        {title: 'Quiz06 5',  image: '/imp/8.png'},
        {title: 'Quiz06 6',  image: '/imp/9.png'},
    ]},
    {"id":"ElVjz_5Odhs", "data": [
        {title: 'Quiz07 1',  image: '/imp/4.png'},
        {title: 'Quiz07 2', image: '/imp/5.png'},
        {title: 'Quiz07 3',  image: '/imp/6.png'},
        {title: 'Quiz07 4', image: '/imp/7.png'},
        {title: 'Quiz07 5',  image: '/imp/8.png'},
        {title: 'Quiz07 6',  image: '/imp/9.png'},
    ]},
    {"id":"_invxKlhGbQ", "data": [
        {title: 'Quiz08 1',  image: '/imp/4.png'},
        {title: 'Quiz08 2', image: '/imp/5.png'},
        {title: 'Quiz08 3',  image: '/imp/6.png'},
        {title: 'Quiz08 4', image: '/imp/7.png'},
        {title: 'Quiz08 5',  image: '/imp/8.png'},
        {title: 'Quiz08 6',  image: '/imp/9.png'},
    ]},
    {"id":"b1k8RdF5u2g", "data": [
        {title: 'Quiz09 1',  image: '/imp/4.png'},
        {title: 'Quiz09 2', image: '/imp/5.png'},
        {title: 'Quiz09 3',  image: '/imp/6.png'},
        {title: 'Quiz09 4', image: '/imp/7.png'},
        {title: 'Quiz09 5',  image: '/imp/8.png'},
        {title: 'Quiz09 6',  image: '/imp/9.png'},
    ]},
    {"id":"WmpUbk24DFk", "data": [
        {title: 'Quiz10 1',  image: '/streamers/liz0n.png'},
        {title: 'Quiz10 2', image: '/streamers/NAMVSEYASNO.png'},
        {title: 'Quiz10 3',  image: '/streamers/Praden.png'},
        {title: 'Quiz10 4', image: '/streamers/roadhouse.png'},
        {title: 'Quiz10 5',  image: '/streamers/SgtGrafoyni.png'},
        {title: 'Quiz10 6',  image: '/streamers/usachman.png'},
    ]}
    ]
};